name: SonarCloud

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
  push:
    branches: ["main"]

jobs:
  build-and-analyze:
    name: Build and analyze (SonarCloud)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # better context for blame/PR analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build, test and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # needed for PR decoration
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}    # your SonarCloud token
        run: >
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.projectKey=INFOM126-Automated-Software-Engineering_2048-Drif
          -Dsonar.organization=infom126-automated-software-engineering
          -Dsonar.sources=src/main/java
          -Dsonar.tests=src/test/java
          -Dsonar.exclusions=**/target/**,**/*.html,**/*.css,**/*.js,**/*.xml
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
          -Dsonar.qualitygate.wait=true
